// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var rocket = "url(\"data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg'  width='40' height='48' viewport='0 0 100 100' style='fill:black;font-size:24px;'><text y='50%'>🚀</text></svg>\") 16 0,auto;";

var lighting = "url(\"assets/voltage.svg\") 16 0,auto;";

exports.rocket = rocket;
exports.lighting = lighting;
/* No side effect */
