// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("./Theme.bs.js");

function addStyles(param) {
  CssJs.$$global("html, body, #__next", [
        CssJs.height(CssJs.pct(100)),
        CssJs.width(CssJs.pct(100)),
        CssJs.padding(CssJs.zero),
        CssJs.margin(CssJs.zero),
        CssJs.backgroundColor(Theme.Colors.black)
      ]);
  CssJs.$$global("html", [
        CssJs.fontSize(CssJs.px(10)),
        CssJs.unsafe("scroll-behavior", "smooth")
      ]);
  return CssJs.$$global("*", [
              CssJs.boxSizing("borderBox"),
              CssJs.selection([CssJs.background(CssJs.rgba(116, 58, 240, {
                              NAME: "percent",
                              VAL: 55.0
                            }))])
            ]);
}

exports.addStyles = addStyles;
/* CssJs Not a pure module */
