// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function useMount(fn) {
  React.useEffect((function () {
          Curry._1(fn, undefined);
          
        }), []);
  
}

exports.useMount = useMount;
/* react Not a pure module */
