// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

function toString(prim) {
  return prim.toString();
}

function map(items, fn) {
  return Belt_Array.mapWithIndex(items, (function (index, item) {
                return Curry._2(fn, item, index);
              }));
}

function str(prim) {
  return prim;
}

exports.toString = toString;
exports.map = map;
exports.str = str;
/* No side effect */
