// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");

var black = CssJs.hex("000000");

var primary = CssJs.hex("FF3358");

var Colors = {
  black: black,
  primary: primary
};

var maxWidth = CssJs.px(1200);

var Constants = {
  maxWidth: maxWidth
};

var ZIndex = {
  aboveAll: 100,
  above: 50
};

var xs = CssJs.rem(0.8);

var sm = CssJs.rem(1.2);

var md = CssJs.rem(1.6);

var lg = CssJs.rem(2.4);

var xlg = CssJs.rem(3.2);

var Spacing = {
  xs: xs,
  sm: sm,
  md: md,
  lg: lg,
  xlg: xlg
};

exports.Colors = Colors;
exports.Constants = Constants;
exports.ZIndex = ZIndex;
exports.Spacing = Spacing;
/* black Not a pure module */
