// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");

var black = "#070707";

var purple = "#743AF0";

var shape01 = "#3C3C3C";

var gray1 = "7D7D7D";

var ColorsRaw = {
  black: black,
  purple: purple,
  shape01: shape01,
  gray1: gray1
};

function toBsHex(color) {
  return CssJs.hex(color.replace("#", ""));
}

var black$1 = toBsHex(black);

var purple$1 = toBsHex(purple);

var shape01$1 = toBsHex(shape01);

var white = toBsHex("FAFAFA");

var gray1$1 = toBsHex(gray1);

var Colors = {
  toBsHex: toBsHex,
  black: black$1,
  purple: purple$1,
  shape01: shape01$1,
  white: white,
  gray1: gray1$1
};

var maxWidth = CssJs.px(1200);

var Constants = {
  maxWidth: maxWidth
};

var ZIndex = {
  aboveAll: 100,
  above: 50,
  base: 10,
  hidden: -1
};

var xs = CssJs.rem(0.8);

var sm = CssJs.rem(1.2);

var md = CssJs.rem(1.6);

var lg = CssJs.rem(2.4);

var xlg = CssJs.rem(3.2);

var Spacing = {
  xs: xs,
  sm: sm,
  md: md,
  lg: lg,
  xlg: xlg
};

var fontFamily = "'Poppins', sans-serif";

exports.ColorsRaw = ColorsRaw;
exports.Colors = Colors;
exports.Constants = Constants;
exports.ZIndex = ZIndex;
exports.Spacing = Spacing;
exports.fontFamily = fontFamily;
/* black Not a pure module */
