// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var Render = require("../../lib/Render.bs.js");
var FAQ_Item = require("./FAQ_Item.bs.js");
var FAQ_Styles = require("./FAQ_Styles.bs.js");
var FAQ_Content = require("./FAQ_Content.bs.js");
var FramerMotion = require("framer-motion");
var ReactIntersectionObserver = require("react-intersection-observer");

var variants_hidden = {
  opacity: 0.0,
  y: 20
};

var variants_visible = {
  opacity: 1.0,
  y: 0,
  transition: {
    duration: 0.6,
    delay: 0.2
  }
};

var variants = {
  hidden: variants_hidden,
  visible: variants_visible
};

function FAQ(Props) {
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  var controls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
          }
          
        }), [inView]);
  return React.createElement("div", {
              className: FAQ_Styles.wrapper
            }, React.createElement(Title.make, {
                  children: "FAQ",
                  innerRef: match[0],
                  animate: {
                    NAME: "controlled",
                    VAL: controls
                  },
                  initial: "hidden",
                  variants: variants
                }), React.createElement(Motion.Div.make, {
                  className: FAQ_Styles.listWrapper,
                  children: Render.map(FAQ_Content.items, (function (item, id) {
                          return React.createElement(FAQ_Item.make, {
                                      title: item.title,
                                      description: item.description,
                                      controls: controls,
                                      id: id,
                                      key: Render.toString(id)
                                    });
                        }))
                }));
}

var FAQItem;

var make = FAQ;

exports.FAQItem = FAQItem;
exports.variants = variants;
exports.make = make;
/* Title Not a pure module */
