// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin4(CssJs.zero, CssJs.auto, CssJs.rem(0.0), CssJs.auto),
      CssJs.padding2(CssJs.rem(12.4), CssJs.zero)
    ]);

var listWrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexWrap("wrap")
    ]);

var faqWrapper = CssJs.style([
      CssJs.flex3(1.0, 0.0, CssJs.pct(50.0)),
      CssJs.nthChild("odd", [CssJs.paddingRight(CssJs.rem(7.0))]),
      CssJs.nthChild("even", [CssJs.paddingLeft(CssJs.rem(7.0))]),
      CssJs.marginBottom(CssJs.rem(6.4))
    ]);

var _title = CssJs.style([
      CssJs.fontSize(CssJs.rem(2.4)),
      CssJs.color(Theme.Colors.white),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 600
          }),
      CssJs.marginBottom(CssJs.rem(1.6))
    ]);

exports.wrapper = wrapper;
exports.listWrapper = listWrapper;
exports.faqWrapper = faqWrapper;
exports._title = _title;
/* wrapper Not a pure module */
