// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Media = require("../../lib/Media.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      Media.xs([
            CssJs.margin4(CssJs.rem(17.2), CssJs.auto, CssJs.zero, CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(3.2)),
            CssJs.after([CssJs.display("none")])
          ]),
      Media.sm([
            CssJs.maxWidth(Theme.Constants.maxWidth),
            CssJs.margin4(CssJs.rem(22.4), CssJs.auto, CssJs.zero, CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(4.6)),
            CssJs.after([CssJs.display("none")])
          ]),
      Media.md([
            CssJs.margin4(CssJs.rem(23.4), CssJs.auto, CssJs.rem(0.0), CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(4.6))
          ]),
      Media.lg([CssJs.after([CssJs.display("block")])])
    ]);

var listWrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexWrap("wrap")
    ]);

var faqWrapper = CssJs.style([
      Media.md([
            CssJs.flex3(1.0, 0.0, CssJs.pct(50.0)),
            CssJs.nthChild("odd", [CssJs.paddingRight(CssJs.rem(7.0))]),
            CssJs.nthChild("even", [CssJs.paddingLeft(CssJs.rem(7.0))])
          ]),
      CssJs.marginBottom(CssJs.rem(6.4))
    ]);

var _title = CssJs.style([
      CssJs.fontSize(CssJs.rem(2.4)),
      CssJs.color(Theme.Colors.white),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 600
          }),
      CssJs.marginBottom(CssJs.rem(1.6))
    ]);

var text = CssJs.style([CssJs.selector("a", [
            CssJs.color(Theme.Colors.pink),
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: Theme.fontFamily
                }),
            CssJs.fontWeight("bold"),
            CssJs.cursor(CssJs.pointer),
            CssJs.opacity(0.7),
            CssJs.transition(300, undefined, undefined, "opacity"),
            CssJs.textDecoration(CssJs.none),
            CssJs.hover([
                  CssJs.opacity(1.0),
                  CssJs.transition(300, undefined, undefined, "opacity")
                ]),
            CssJs.color(Theme.Colors.purple)
          ])]);

exports.wrapper = wrapper;
exports.listWrapper = listWrapper;
exports.faqWrapper = faqWrapper;
exports._title = _title;
exports.text = text;
/* wrapper Not a pure module */
