// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var items = [
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  },
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  },
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  },
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  },
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  },
  {
    title: "O que preciso saber para o curso?",
    description: "Um conhecimento básico de JavaScript/React é necessário para maior entendimento do curso, mas todo o conteúdo será explicado em detalhes e todas as perguntas/dúvidas serão respondidas."
  }
];

exports.items = items;
/* No side effect */
