// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Render = require("../../lib/Render.bs.js");

function makeTelegramUrl(username) {
  return "https://t.me/" + username + "?text=Ol%C3%A1!%20Quero%20saber%20mais%20sobre%20o%20curso%20ES2077";
}

var items = [
  {
    title: "Quais conhecimentos são necessários para fazer o curso?",
    description: Render.str("Não é obrigatório saber React ou JavaScript, no entanto seria interessante ter pelo menos o básico das duas tecnologias para absorver melhor o conteúdo.")
  },
  {
    title: "Quanto tempo tenho para assistir as aulas?",
    description: Render.str("Leve o tempo que quiser para fazer o curso, o acesso é vitalício.")
  },
  {
    title: "O curso possui certificado?",
    description: Render.str("Sim! O curso possui certificado e você poderá baixá-lo assim que finalizar todos os módulos do curso.")
  },
  {
    title: "Onde o conteúdo será disponibilizado?",
    description: Render.str("Todo o conteúdo referente ao curso será disponibilizado na Udemy.")
  },
  {
    title: "Sou aluno da primeira versão do curso, tenho acesso a esta versão também?",
    description: Render.str("Como aluno do primeiro curso, você terá acesso apenas ao primeiro módulo deste curso, que possui o mesmo conteúdo que a primeira versão, porém com atualizações e novos materiais produzidos para esta versão.")
  },
  {
    title: "Tenho outras dúvidas",
    description: React.createElement(React.Fragment, undefined, Render.str("\n          Caso você tenha outras dúvidas relacionadas ao curso, \n          ou se você é aluno da primeira versão do curso e tem alguma dúvida você pode chamar o\n        "), React.createElement("a", {
              href: "https://t.me/" + "vmarcosp" + "?text=Ol%C3%A1!%20Quero%20saber%20mais%20sobre%20o%20curso%20ES2077"
            }, Render.str(" Marcos")), Render.str(" e o"), React.createElement("a", {
              href: "https://t.me/" + "gabriel" + "?text=Ol%C3%A1!%20Quero%20saber%20mais%20sobre%20o%20curso%20ES2077"
            }, Render.str(" Gabriel")), Render.str(" pelo telegram."))
  }
];

exports.makeTelegramUrl = makeTelegramUrl;
exports.items = items;
/* items Not a pure module */
