// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function $$Text(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, children);
}

var make = $$Text;

exports.make = make;
/* react Not a pure module */
