// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Menu_Styles = require("./Menu_Styles.bs.js");

function Menu_BurgerButton(Props) {
  var isOpen = Props.isOpen;
  var onClick = Props.onClick;
  return React.createElement("button", {
              className: Menu_Styles.burgerButton(isOpen),
              onClick: onClick
            });
}

var S;

var make = Menu_BurgerButton;

exports.S = S;
exports.make = make;
/* react Not a pure module */
