// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var Menu_Styles = require("./Menu_Styles.bs.js");
var Menu_BurgerButton = require("./Menu_BurgerButton.bs.js");

var links = [
  {
    sectionId: "",
    label: "Início"
  },
  {
    sectionId: "",
    label: "O que é ReScript?"
  },
  {
    sectionId: "",
    label: "Sobre o curso"
  },
  {
    sectionId: "",
    label: "Depoimentos"
  },
  {
    sectionId: "",
    label: "Apoiadores"
  },
  {
    sectionId: "",
    label: "FAQ"
  }
];

function Menu$Link(Props) {
  var label = Props.label;
  var href = Props.href;
  return React.createElement("li", {
              className: Menu_Styles.link
            }, React.createElement("a", {
                  href: href
                }, label));
}

var Link = {
  make: Menu$Link
};

function Menu(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setIsOpen = match[1];
  var isOpen = match[0];
  var toggleMenu = function (param) {
    return Curry._1(setIsOpen, (function (param) {
                  return !isOpen;
                }));
  };
  var classes = Menu_Styles.createClasses(isOpen);
  return React.createElement(React.Fragment, undefined, React.createElement(Menu_BurgerButton.make, {
                  isOpen: isOpen,
                  onClick: toggleMenu
                }), React.createElement("div", {
                  className: classes.overlay
                }, React.createElement("div", {
                      className: classes.menuWrapper
                    }, React.createElement("ul", undefined, Render.map(links, (function (param, id) {
                                return React.createElement(Menu$Link, {
                                            label: param.label,
                                            href: param.sectionId,
                                            key: Render.toString(id)
                                          });
                              }))), React.createElement("a", {
                          className: classes.email,
                          href: "mailto:contato@es77.dev"
                        }, "contato@es77.dev"))));
}

var S;

var BurgerButton;

var make = Menu;

exports.S = S;
exports.BurgerButton = BurgerButton;
exports.links = links;
exports.Link = Link;
exports.make = make;
/* react Not a pure module */
