// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");
var Css_Js_Core = require("bs-css/src/Css_Js_Core.bs.js");

function createClasses(isOpen) {
  var overlay = CssJs.style([
        CssJs.position(CssJs.fixed),
        CssJs.width(CssJs.pct(100.0)),
        CssJs.height(CssJs.pct(100.0)),
        CssJs.left(CssJs.zero),
        CssJs.top(isOpen ? CssJs.zero : CssJs.rem(10.0)),
        CssJs.padding(CssJs.zero),
        CssJs.margin(CssJs.zero),
        CssJs.zIndex(Theme.ZIndex.above),
        CssJs.backgroundColor(CssJs.rgba(7, 7, 7, {
                  NAME: "num",
                  VAL: 0.85
                })),
        CssJs.visibility(isOpen ? CssJs.visible : CssJs.hidden),
        CssJs.opacity(isOpen ? 1.0 : 0.0),
        CssJs.transitionDuration(400),
        CssJs.display("flex"),
        CssJs.alignItems("center")
      ]);
  var menuWrapper = CssJs.style([
        CssJs.maxWidth(Theme.Constants.maxWidth),
        CssJs.width(CssJs.pct(100.0)),
        CssJs.margin2(CssJs.zero, CssJs.auto),
        CssJs.display("flex"),
        CssJs.alignItems("flexEnd"),
        CssJs.justifyContent(CssJs.spaceBetween)
      ]);
  var email = CssJs.style([
        CssJs.color(Theme.Colors.gray1),
        CssJs.fontFamily({
              NAME: "custom",
              VAL: Theme.fontFamily
            }),
        CssJs.fontWeight({
              NAME: "num",
              VAL: 500
            }),
        CssJs.fontSize(CssJs.rem(1.8)),
        CssJs.cursor(CssJs.pointer),
        CssJs.textDecoration("none"),
        CssJs.transition(300, undefined, undefined, "color"),
        CssJs.hover([CssJs.color(Theme.Colors.white)])
      ]);
  return {
          menuWrapper: menuWrapper,
          overlay: overlay,
          email: email
        };
}

var link = CssJs.style([
      CssJs.listStyleType(CssJs.none),
      CssJs.marginBottom(CssJs.rem(4.2)),
      CssJs.position(CssJs.relative),
      CssJs.selector("> a", [
            CssJs.fontSize(CssJs.rem(3.2)),
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 700
                }),
            CssJs.textDecoration(CssJs.none),
            CssJs.color(Theme.Colors.white),
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: Theme.fontFamily
                }),
            CssJs.hover([
                  CssJs.color(Theme.Colors.purple),
                  CssJs.transition(400, undefined, undefined, "width")
                ]),
            CssJs.overflow(CssJs.hidden),
            CssJs.unsafe("background", "linear-gradient(to right, " + Theme.ColorsRaw.purple + ", " + Theme.ColorsRaw.purple + " 50%, white 50%)"),
            CssJs.unsafe("background-clip", "text"),
            CssJs.unsafe("-webkit-background-clip", "text"),
            CssJs.unsafe("-webkit-text-fill-color", "transparent"),
            CssJs.transition(200, undefined, undefined, "background-position"),
            CssJs.backgroundSize({
                  NAME: "size",
                  VAL: [
                    CssJs.pct(200.0),
                    CssJs.pct(100.0)
                  ]
                }),
            CssJs.backgroundPosition({
                  NAME: "percent",
                  VAL: 100.0
                }),
            CssJs.transitions([
                  Css_Js_Core.Transition.shorthand(400, undefined, undefined, "padding"),
                  Css_Js_Core.Transition.shorthand(400, undefined, undefined, "background-position")
                ]),
            CssJs.after([
                  CssJs.contentRule({
                        NAME: "text",
                        VAL: " "
                      }),
                  CssJs.width(CssJs.rem(0.0)),
                  CssJs.height(CssJs.rem(0.6)),
                  CssJs.backgroundColor(Theme.Colors.purple),
                  CssJs.position(CssJs.absolute),
                  CssJs.left(CssJs.zero),
                  CssJs.top(CssJs.pct(50.0)),
                  CssJs.transform(CssJs.translateY(CssJs.pct(-50.0))),
                  CssJs.transition(400, undefined, undefined, "width")
                ]),
            CssJs.hover([
                  CssJs.unsafe("background-position", "0% 100%"),
                  CssJs.paddingLeft(CssJs.rem(4.8)),
                  CssJs.transitionDuration(400),
                  CssJs.transitions([
                        Css_Js_Core.Transition.shorthand(400, undefined, undefined, "padding"),
                        Css_Js_Core.Transition.shorthand(400, undefined, undefined, "background-position")
                      ]),
                  CssJs.after([
                        CssJs.width(CssJs.rem(3.2)),
                        CssJs.transition(400, undefined, undefined, "width")
                      ])
                ])
          ])
    ]);

function burgerButton(isOpen) {
  return CssJs.style([
              CssJs.padding(CssJs.zero),
              CssJs.margin(CssJs.zero),
              CssJs.borderStyle(CssJs.none),
              CssJs.outlineStyle(CssJs.none),
              CssJs.position(CssJs.relative),
              CssJs.height(CssJs.px(12)),
              CssJs.width(CssJs.px(25)),
              CssJs.backgroundColor(CssJs.transparent),
              CssJs.cursor(CssJs.pointer),
              CssJs.overflow(CssJs.visible),
              CssJs.zIndex(Theme.ZIndex.aboveAll),
              CssJs.selector("&:after,&:before", [
                    CssJs.contentRule({
                          NAME: "text",
                          VAL: " "
                        }),
                    CssJs.height(CssJs.px(2)),
                    CssJs.width(CssJs.rem(2.5)),
                    CssJs.backgroundColor(Theme.Colors.shape01),
                    CssJs.position(CssJs.absolute),
                    CssJs.borderRadius(CssJs.px(2)),
                    CssJs.transition(200, undefined, undefined, "transform")
                  ]),
              CssJs.after([
                    CssJs.left(CssJs.zero),
                    CssJs.bottom(isOpen ? CssJs.px(5) : CssJs.px(0)),
                    CssJs.transform(isOpen ? CssJs.rotateZ(CssJs.deg(-45.0)) : CssJs.rotateZ(CssJs.deg(0.0)))
                  ]),
              CssJs.before([
                    CssJs.left(CssJs.zero),
                    CssJs.top(isOpen ? CssJs.px(5) : CssJs.px(0)),
                    CssJs.transform(isOpen ? CssJs.rotateZ(CssJs.deg(45.0)) : CssJs.rotateZ(CssJs.deg(0.0)))
                  ])
            ]);
}

exports.createClasses = createClasses;
exports.link = link;
exports.burgerButton = burgerButton;
/* link Not a pure module */
