// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");

var heroText = React.createElement(React.Fragment, undefined, Render.str("Aprenda uma linguagem"), React.createElement($$Text.Span.make, {
          children: " funcional "
        }), Render.str("focada em "), React.createElement($$Text.Span.make, {
          children: "React"
        }));

exports.heroText = heroText;
/* heroText Not a pure module */
