// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Animated = require("./Animated");
var Hero_Styles = require("./Hero_Styles.bs.js");

var make = Animated.Symbol;

var $$Symbol = {
  make: make
};

var make$1 = Animated.Title;

var Title = {
  make: make$1
};

function Hero(Props) {
  return React.createElement("div", {
              className: Hero_Styles.wrapper
            }, React.createElement("div", {
                  className: Hero_Styles.symbolWrapper
                }, React.createElement(make, {})), React.createElement(make$1, {
                  children: null,
                  className: Hero_Styles.text
                }, React.createElement($$Text.make, {
                      children: "Aprenda uma linguagem"
                    }), React.createElement($$Text.make, {
                      children: " funcional ",
                      tag: "span"
                    }), React.createElement($$Text.make, {
                      children: "e focada em "
                    }), React.createElement($$Text.make, {
                      children: "React",
                      tag: "span"
                    })));
}

var Styles;

var make$2 = Hero;

exports.Styles = Styles;
exports.$$Symbol = $$Symbol;
exports.Title = Title;
exports.make = make$2;
/* make Not a pure module */
