// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin2(CssJs.rem(10.0), CssJs.auto),
      CssJs.display("flex"),
      CssJs.flexDirection(CssJs.column),
      CssJs.alignItems(CssJs.center),
      CssJs.justifyContent(CssJs.center)
    ]);

var symbolWrapper = CssJs.style([CssJs.width(CssJs.rem(35.0))]);

var text = CssJs.style([
      CssJs.color(Theme.Colors.white),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontSize(CssJs.rem(6.0)),
      CssJs.textAlign("center"),
      CssJs.maxWidth(CssJs.px(1000)),
      CssJs.position(CssJs.relative),
      CssJs.top(CssJs.px(-100)),
      CssJs.selector("> span", [
            CssJs.unsafe("background", "linear-gradient(180deg, #FF89DE -17.85%, #FF68D5 30.22%, #9361FF 77.87%, #743AF0 118.28%)"),
            CssJs.unsafe("background-clip", "text"),
            CssJs.unsafe("-webkit-background-clip", "text"),
            CssJs.unsafe("-webkit-text-fill-color", "transparent")
          ])
    ]);

exports.wrapper = wrapper;
exports.symbolWrapper = symbolWrapper;
exports.text = text;
/* wrapper Not a pure module */
