// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Media = require("../../lib/Media.bs.js");
var Theme = require("../../lib/Theme.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.display("flex"),
      CssJs.flexDirection(CssJs.column),
      CssJs.alignItems(CssJs.center),
      CssJs.justifyContent(CssJs.center),
      CssJs.position(CssJs.relative),
      Media.xs([
            CssJs.margin4(CssJs.rem(5.2), CssJs.auto, CssJs.rem(0.0), CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(3.2))
          ]),
      Media.sm([
            CssJs.margin4(CssJs.rem(5.2), CssJs.auto, CssJs.rem(0.0), CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(3.2))
          ]),
      Media.sm([CssJs.margin4(CssJs.rem(7.2), CssJs.auto, CssJs.rem(0.0), CssJs.auto)])
    ]);

var symbolWrapper = CssJs.style([
      Media.xs([CssJs.width(CssJs.rem(28.0))]),
      Media.sm([CssJs.width(CssJs.rem(35.0))])
    ]);

var text = CssJs.style([
      CssJs.color(Theme.Colors.white),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.textAlign("center"),
      CssJs.position(CssJs.relative),
      CssJs.top(CssJs.px(-100)),
      CssJs.selector("> span", Belt_Array.concat([CssJs.background(Theme.Colors.gradient)], Theme.Constants.clipBackground)),
      Media.xs([CssJs.fontSize(CssJs.rem(3.2))]),
      Media.sm([CssJs.fontSize(CssJs.rem(3.8))]),
      Media.md([
            CssJs.maxWidth(CssJs.rem(60.0)),
            CssJs.fontSize(CssJs.rem(4.2))
          ]),
      Media.lg([
            CssJs.maxWidth(CssJs.rem(75.2)),
            CssJs.fontSize(CssJs.rem(5.2))
          ]),
      Media.xl([
            CssJs.fontSize(CssJs.rem(5.8)),
            CssJs.maxWidth(CssJs.px(900))
          ])
    ]);

var arrowAnimation = CssJs.keyframes([
      [
        0,
        [CssJs.transform(CssJs.translateY(CssJs.px(5)))]
      ],
      [
        50,
        [CssJs.transform(CssJs.translateY(CssJs.zero))]
      ],
      [
        100,
        [CssJs.transform(CssJs.translateY(CssJs.px(5)))]
      ]
    ]);

var button = CssJs.style(Belt_Array.concat([
          CssJs.padding(CssJs.zero),
          CssJs.margin(CssJs.zero),
          CssJs.outlineStyle(CssJs.none),
          CssJs.borderStyle(CssJs.none),
          CssJs.background(Theme.Colors.gradient),
          CssJs.fontFamily({
                NAME: "custom",
                VAL: Theme.fontFamily
              }),
          CssJs.fontSize(CssJs.rem(1.8)),
          CssJs.fontWeight({
                NAME: "num",
                VAL: 600
              }),
          CssJs.position(CssJs.relative),
          CssJs.cursor(CssJs.pointer),
          CssJs.textDecoration(CssJs.none),
          Media.xs([CssJs.top(CssJs.px(-20))]),
          Media.lg([
                CssJs.position(CssJs.absolute),
                CssJs.bottom(CssJs.rem(5.6))
              ]),
          CssJs.after([
                CssJs.contentRule({
                      NAME: "url",
                      VAL: "assets/arrow-down.svg"
                    }),
                CssJs.position(CssJs.absolute),
                CssJs.bottom(CssJs.rem(-0.5)),
                CssJs.width(CssJs.rem(2.0)),
                CssJs.height(CssJs.rem(1.0)),
                CssJs.left(CssJs.pct(50.0)),
                CssJs.marginLeft(CssJs.rem(-1.0)),
                CssJs.animation(1000, undefined, undefined, undefined, undefined, undefined, "infinite", arrowAnimation)
              ])
        ], Theme.Constants.clipBackground));

var $$Array;

exports.$$Array = $$Array;
exports.wrapper = wrapper;
exports.symbolWrapper = symbolWrapper;
exports.text = text;
exports.arrowAnimation = arrowAnimation;
exports.button = button;
/* wrapper Not a pure module */
