// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var AboutUs_Styles = require("./AboutUs_Styles.bs.js");

function AboutUs_Card(Props) {
  var name = Props.name;
  var description = Props.description;
  var role = Props.role;
  var src = Props.photo;
  return React.createElement("div", {
              className: AboutUs_Styles.card
            }, React.createElement("img", {
                  className: AboutUs_Styles.photo,
                  alt: name,
                  src: src
                }), React.createElement("p", {
                  className: AboutUs_Styles.title
                }, name), React.createElement("p", {
                  className: AboutUs_Styles.subtitle
                }, role), React.createElement($$Text.P.make, {
                  children: description
                }));
}

var make = AboutUs_Card;

exports.make = make;
/* Text Not a pure module */
