// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin4(CssJs.zero, CssJs.auto, CssJs.rem(0.0), CssJs.auto),
      CssJs.padding2(CssJs.rem(12.4), CssJs.zero),
      CssJs.display("flex"),
      CssJs.justifyContent(CssJs.center),
      CssJs.flexDirection(CssJs.column),
      CssJs.alignItems(CssJs.center),
      CssJs.position(CssJs.relative),
      CssJs.after([
            CssJs.contentRule({
                  NAME: "url",
                  VAL: "assets/triangle.svg"
                }),
            CssJs.width(CssJs.rem(40.2)),
            CssJs.height(CssJs.rem(40.2)),
            CssJs.position(CssJs.absolute),
            CssJs.zIndex(Theme.ZIndex.base - 1 | 0),
            CssJs.right(CssJs.zero),
            CssJs.bottom(CssJs.rem(10.0))
          ]),
      CssJs.before([])
    ]);

var triangle = CssJs.style([
      CssJs.position(CssJs.absolute),
      CssJs.zIndex(Theme.ZIndex.base - 1 | 0),
      CssJs.left(CssJs.zero)
    ]);

var card = CssJs.style([
      CssJs.background(Theme.Colors.shape02),
      CssJs.color(CssJs.white),
      CssJs.display("flex"),
      CssJs.justifyContent(CssJs.center),
      CssJs.flexDirection(CssJs.column),
      CssJs.alignItems(CssJs.center),
      CssJs.textAlign(CssJs.center),
      CssJs.padding2(CssJs.rem(5.6), CssJs.rem(5.6)),
      CssJs.maxWidth(CssJs.rem(40.0)),
      CssJs.borderRadius(Theme.Radius.xs),
      CssJs.firstChild([CssJs.marginRight(CssJs.rem(3.2))]),
      CssJs.position(CssJs.relative),
      CssJs.zIndex(Theme.ZIndex.base)
    ]);

var photo = CssJs.style([
      CssJs.width(CssJs.rem(13.5)),
      CssJs.height(CssJs.rem(13.5)),
      CssJs.borderRadius(CssJs.pct(50.0)),
      CssJs.marginBottom(CssJs.rem(2.4))
    ]);

var cardsContainer = CssJs.style([
      CssJs.display("flex"),
      CssJs.marginTop(CssJs.rem(5.6))
    ]);

var title = CssJs.style([
      CssJs.color(Theme.Colors.white),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 700
          }),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontSize(CssJs.rem(1.8)),
      CssJs.margin(CssJs.zero),
      CssJs.marginBottom(CssJs.px(4))
    ]);

var subtitle = CssJs.style([
      CssJs.color(Theme.Colors.gray1),
      CssJs.fontSize(CssJs.rem(1.6)),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.margin(CssJs.zero)
    ]);

var iconsWrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.marginTop(CssJs.rem(1.6))
    ]);

var icon = CssJs.style([
      CssJs.width(CssJs.rem(2.4)),
      CssJs.display(CssJs.block),
      CssJs.selector(":not(:last-child)", [CssJs.marginRight(CssJs.rem(2.0))]),
      CssJs.selector("svg > path", [CssJs.transition(300, undefined, undefined, "fill")]),
      CssJs.hover([CssJs.selector("svg > path", [
                  CssJs.transition(300, undefined, undefined, "fill"),
                  CssJs.unsafe("fill", Theme.ColorsRaw.purple)
                ])])
    ]);

exports.wrapper = wrapper;
exports.triangle = triangle;
exports.card = card;
exports.photo = photo;
exports.cardsContainer = cardsContainer;
exports.title = title;
exports.subtitle = subtitle;
exports.iconsWrapper = iconsWrapper;
exports.icon = icon;
/* wrapper Not a pure module */
