// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var AboutUs_Card = require("./AboutUs_Card.bs.js");
var AboutUs_Styles = require("./AboutUs_Styles.bs.js");

function AboutUs(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("img", {
                  className: AboutUs_Styles.triangle,
                  src: "assets/triangle-2.svg"
                }), React.createElement("div", {
                  className: AboutUs_Styles.wrapper
                }, React.createElement(Title.make, {
                      children: "Quem somos nós"
                    }), React.createElement("div", {
                      className: AboutUs_Styles.cardsContainer
                    }, React.createElement(AboutUs_Card.make, {
                          name: "Marcos Oliveira",
                          description: "Eu como instrutor, prezo sempre pela didática acima de tudo. Existem muitos cursos onde a qualidade de áudio/imagem/edição são o grande foco, mas o ensino nem tanto. Com o Vedovelli posso dizer que é tudo muito bem feito, em todos os aspectos.",
                          role: "Developer na brainn.co",
                          photo: "assets/marcos.jpeg"
                        }), React.createElement(AboutUs_Card.make, {
                          name: "Gabriel Rubens",
                          description: "Eu como instrutor, prezo sempre pela didática acima de tudo. Existem muitos cursos onde a qualidade de áudio/imagem/edição são o grande foco, mas o ensino nem tanto. Com o Vedovelli posso dizer que é tudo muito bem feito, em todos os aspectos.",
                          role: "CTO na Astrocoders",
                          photo: "assets/gabriel.jpeg"
                        }))));
}

var Card;

var make = AboutUs;

exports.Card = Card;
exports.make = make;
/* Title Not a pure module */
