// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var $$Image = require("next/image").default;
var AboutUs_Icons = require("./AboutUs_Icons.bs.js");
var FramerMotion = require("framer-motion");
var AboutUs_Styles = require("./AboutUs_Styles.bs.js");
var ReactIntersectionObserver = require("react-intersection-observer");

function variants(x) {
  return {
          hidden: {
            opacity: 0.0,
            x: x
          },
          visible: {
            opacity: 1.0,
            x: 0,
            transition: {
              duration: 0.6,
              delay: 0.35
            }
          }
        };
}

function AboutUs_Card(Props) {
  var name = Props.name;
  var description = Props.description;
  var role = Props.role;
  var src = Props.photo;
  var github = Props.github;
  var telegram = Props.telegram;
  var twitter = Props.twitter;
  var initialX = Props.initialX;
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  var controls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
          }
          
        }), [inView]);
  return React.createElement(Motion.Div.make, {
              className: AboutUs_Styles.card,
              initial: "hidden",
              variants: variants(initialX),
              animate: {
                NAME: "controlled",
                VAL: controls
              },
              innerRef: match[0],
              children: null
            }, React.createElement("div", {
                  className: AboutUs_Styles.photo
                }, React.createElement($$Image, {
                      src: src,
                      width: "120",
                      height: "120",
                      alt: name
                    })), React.createElement("p", {
                  className: AboutUs_Styles.title
                }, name), React.createElement("p", {
                  className: AboutUs_Styles.subtitle
                }, role), React.createElement("div", {
                  className: AboutUs_Styles.iconsWrapper
                }, React.createElement("a", {
                      "aria-label": "github",
                      className: AboutUs_Styles.icon,
                      href: github,
                      rel: "noopener noreferrer"
                    }, React.createElement(AboutUs_Icons.Github.make, {})), React.createElement("a", {
                      "aria-label": "telegram",
                      className: AboutUs_Styles.icon,
                      href: telegram,
                      rel: "noopener noreferrer"
                    }, React.createElement(AboutUs_Icons.Telegram.make, {})), React.createElement("a", {
                      "aria-label": "twitter ",
                      className: AboutUs_Styles.icon,
                      href: twitter,
                      rel: "noopener noreferrer"
                    }, React.createElement(AboutUs_Icons.Twitter.make, {}))), React.createElement($$Text.P.make, {
                  children: description
                }));
}

var Icons;

var make = AboutUs_Card;

exports.Icons = Icons;
exports.variants = variants;
exports.make = make;
/* Text Not a pure module */
