// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Req = {};

var Res = {};

var GetServerSideProps = {
  Req: Req,
  Res: Res
};

var GetStaticProps = {};

var GetStaticPaths = {};

var Link = {};

var Events = {};

var Router = {
  Events: Events
};

var Head = {};

var $$Error = {};

var Dynamic = {};

var $$Image = {};

exports.GetServerSideProps = GetServerSideProps;
exports.GetStaticProps = GetStaticProps;
exports.GetStaticPaths = GetStaticPaths;
exports.Link = Link;
exports.Router = Router;
exports.Head = Head;
exports.$$Error = $$Error;
exports.Dynamic = Dynamic;
exports.$$Image = $$Image;
/* No side effect */
