// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var ReviewCard = require("./ReviewCard.bs.js");
var ReactSlick = require("react-slick").default;
var Review_Styles = require("./Review_Styles.bs.js");
var Reviews_Content = require("./Reviews_Content.bs.js");

function Reviews(Props) {
  return React.createElement("div", {
              className: Review_Styles.wrapper
            }, React.createElement(Title.make, {
                  children: "Pessoas que acreditam no curso"
                }), React.createElement(ReactSlick, {
                  dots: true,
                  slidesToShow: 2,
                  children: Render.map(Reviews_Content.highlights, (function (review, id) {
                          return React.createElement(ReviewCard.make, {
                                      photo: review.photo,
                                      name: review.name,
                                      role: review.role,
                                      description: review.description,
                                      key: Render.toString(id)
                                    });
                        }))
                }));
}

var make = Reviews;

exports.make = make;
/* Title Not a pure module */
