// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var highlights = [
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Vitor Mendrone",
    role: "CTO na Portolab",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Vitor Mendrone",
    role: "CTO na Portolab",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Vitor Mendrone",
    role: "CTO na Portolab",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  },
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na brainn.co",
    photo: "assets/reviews/daciuk.png",
    description: "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua oportunidade de aprender - de verdade - com quem entende do assunto 😄"
  }
];

exports.highlights = highlights;
/* No side effect */
