// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");

function Reviews_Content$TextWrapper(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, "\u00a0 \u00a0 \u00a0 \u00a0", children);
}

var TextWrapper = {
  make: Reviews_Content$TextWrapper
};

var highlights = [
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na Brainn Co.",
    photo: "assets/reviews/daciuk.png",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua", React.createElement($$Text.Span.make, {
              children: " oportunidade de aprender de verdade "
            }), "com quem entende do assunto 😄")
  },
  {
    name: "Guilherme Decampo",
    role: "CEO na Astrocoders",
    photo: "assets/reviews/guilherme.jpeg",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, "Nos últimos anos, o Gabriel tem liderado a adoção de ReScript na Astrocoders. Sem dúvidas, hoje ele é uma das principais referências que mais domina e conhece ReScript no Brasil. Tenho certeza que se você quer aprender ReScript, este é o ", React.createElement($$Text.Span.make, {
              children: "melhor material de aprendizado disponível no mercado "
            }), "🚀")
  },
  {
    name: "Diogo Moretti",
    role: "Developer Relations na Brainn Co.",
    photo: "assets/reviews/moretti.jpeg",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua", React.createElement($$Text.Span.make, {
              children: " oportunidade de aprender de verdade "
            }), "com quem entende do assunto 😄")
  },
  {
    name: "Vitor Mendrone",
    role: "CTO na Portolab",
    photo: "assets/reviews/mendrone.jpeg",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, "Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua", React.createElement($$Text.Span.make, {
              children: " oportunidade de aprender de verdade "
            }), "com quem entende do assunto 😄")
  }
];

exports.TextWrapper = TextWrapper;
exports.highlights = highlights;
/* highlights Not a pure module */
