// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin2(CssJs.zero, CssJs.auto)
    ]);

var card = CssJs.style([
      CssJs.backgroundColor(Theme.Colors.shape02),
      CssJs.borderRadius(CssJs.px(6)),
      CssJs.display("flex"),
      CssJs.flexDirection(CssJs.column),
      CssJs.padding(CssJs.rem(5.2))
    ]);

var _photo = CssJs.style([
      CssJs.width(CssJs.rem(10.0)),
      CssJs.height(CssJs.rem(10.0)),
      CssJs.borderRadius(CssJs.pct(50.0)),
      CssJs.marginRight(CssJs.rem(2.4))
    ]);

var _name = CssJs.style([
      CssJs.color(Theme.Colors.white),
      CssJs.fontSize(CssJs.rem(1.8)),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 700
          }),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.marginBottom(CssJs.rem(0.4))
    ]);

var _role = CssJs.style([
      CssJs.color(Theme.Colors.gray1),
      CssJs.fontSize(CssJs.rem(1.6)),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 500
          }),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.margin(CssJs.zero)
    ]);

var cardHeader = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems(CssJs.center)
    ]);

var _description = CssJs.style([
      CssJs.position(CssJs.relative),
      CssJs.paddingLeft(CssJs.rem(2.6)),
      CssJs.marginTop(CssJs.rem(3.2)),
      CssJs.before([
            CssJs.contentRule({
                  NAME: "url",
                  VAL: "assets/quotes.svg"
                }),
            CssJs.position(CssJs.absolute),
            CssJs.top(CssJs.px(-3)),
            CssJs.left(CssJs.zero),
            CssJs.width(CssJs.rem(2.0)),
            CssJs.height(CssJs.rem(2.0)),
            CssJs.whiteSpace("pre")
          ])
    ]);

exports.wrapper = wrapper;
exports.card = card;
exports._photo = _photo;
exports._name = _name;
exports._role = _role;
exports.cardHeader = cardHeader;
exports._description = _description;
/* wrapper Not a pure module */
