// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function Reviews_Content$TextWrapper(Props) {
  var children = Props.children;
  return React.createElement(React.Fragment, undefined, Render.str("\u00a0 \u00a0 \u00a0 \u00a0"), children);
}

var TextWrapper = {
  make: Reviews_Content$TextWrapper
};

var highlights = [
  {
    name: "Fernando Daciuk",
    role: "Tech Lead na Brainn Co.",
    photo: "/assets/reviews/daciuk.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("Tive o prazer de trabalhar com o Marcos em projetos recentes, e é impossível não ver o brilho nos olhos quando ele está falando de Programação Funcional, JavaScript, React e Rescript. Esse curso é a sua"), React.createElement($$Text.Span.make, {
              children: " oportunidade de aprender de verdade "
            }), Render.str("com quem entende do assunto 😄")),
    translatedDescription: undefined
  },
  {
    name: "Guilherme Decampo",
    role: "CEO na Astrocoders",
    photo: "/assets/reviews/guilherme.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("Nos últimos anos, o Gabriel tem liderado a adoção de ReScript na Astrocoders. Sem dúvidas, hoje ele é uma das principais referências que mais domina e conhece ReScript no Brasil. Tenho certeza que se você quer aprender ReScript, este é o "), React.createElement($$Text.Span.make, {
              children: "melhor material de aprendizado disponível no mercado "
            }), Render.str("🚀")),
    translatedDescription: undefined
  },
  {
    name: "Gabriel Nordeborn",
    role: "Partner na Arizon Consulting",
    photo: "/assets/reviews/zth.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("Gabriel does not merely have a fantastic first name (😂), he’s also an integral part of the ReScript community, having built "), React.createElement($$Text.Span.make, {
              children: "excellent libraries like ReForm, lenses-ppx and more"
            }), Render.str(". Having Gabriel by your side on your ReScript journey "), React.createElement($$Text.Span.make, {
              children: "means you’re in excellent hands!"
            })),
    translatedDescription: Caml_option.some(React.createElement(Reviews_Content$TextWrapper, {
              children: null
            }, Render.str("Gabriel não tem apenas um nome incrível (😂), ele também é parte integrante da comunidade ReScript, tendo construído "), React.createElement($$Text.Span.make, {
                  children: "bibliotecas excelentes como ReForm, lenses-ppx e muito mais"
                }), Render.str(". Ter Gabriel ao seu lado em sua jornada ReScript "), React.createElement($$Text.Span.make, {
                  children: "significa que você está em excelentes mãos!"
                })))
  },
  {
    name: "Vitor Mendrone",
    role: "Head of Engineering na Portolab",
    photo: "/assets/reviews/mendrone.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("Além de ser um dos desenvolvedores mais brilhantes com quem já trabalhei, posso dizer que o conhecimento do Marcos em "), React.createElement($$Text.Span.make, {
              children: "ReScript"
            }), Render.str(" e "), React.createElement($$Text.Span.make, {
              children: "Programação Funcional"
            }), Render.str(" como um todo é impressionante, muito acima da média e"), React.createElement($$Text.Span.make, {
              children: " caminha de mãos dadas com a boa didática que ele desenvolveu sendo um evangelizador informal da linguagem. "
            })),
    translatedDescription: undefined
  }
];

var studentReviews = [
  {
    name: "João Miguel",
    role: "Developer na Lukin",
    photo: "/assets/reviews/daciuk.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("O curso foi incrível! Não encontrei nenhum curso que ensinasse tão bem "), React.createElement("span", undefined, Render.str("programação funcional de uma maneira prática e descomplicada")), Render.str(". Certamente a próxima versão será ainda melhor que a primeira!")),
    translatedDescription: undefined
  },
  {
    name: "João Miguel",
    role: "Developer na Lukin",
    photo: "/assets/reviews/daciuk.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("O curso foi incrível! Não encontrei nenhum curso que ensinasse tão bem "), React.createElement("span", undefined, Render.str("programação funcional de uma maneira prática e descomplicada")), Render.str(". Certamente a próxima versão será ainda melhor que a primeira!")),
    translatedDescription: undefined
  },
  {
    name: "João Miguel",
    role: "Developer na Lukin",
    photo: "/assets/reviews/daciuk.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("O curso foi incrível! Não encontrei nenhum curso que ensinasse tão bem "), React.createElement("span", undefined, Render.str("programação funcional de uma maneira prática e descomplicada")), Render.str(". Certamente a próxima versão será ainda melhor que a primeira!")),
    translatedDescription: undefined
  },
  {
    name: "João Miguel",
    role: "Developer na Lukin",
    photo: "/assets/reviews/daciuk.webp",
    description: React.createElement(Reviews_Content$TextWrapper, {
          children: null
        }, Render.str("O curso foi incrível! Não encontrei nenhum curso que ensinasse tão bem "), React.createElement("span", undefined, Render.str("programação funcional de uma maneira prática e descomplicada")), Render.str(". Certamente a próxima versão será ainda melhor que a primeira!")),
    translatedDescription: undefined
  }
];

exports.TextWrapper = TextWrapper;
exports.highlights = highlights;
exports.studentReviews = studentReviews;
/* highlights Not a pure module */
