// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var ReviewItem = require("./ReviewItem.bs.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Review_Styles = require("./Review_Styles.bs.js");
var FramerMotion = require("framer-motion");
var Reviews_Content = require("./Reviews_Content.bs.js");
var ReactIntersectionObserver = require("react-intersection-observer");

var variants_hidden = {
  opacity: 0.0,
  y: 20
};

var variants_visible = {
  opacity: 1.0,
  y: 0,
  transition: {
    duration: 0.6,
    delay: 0.2
  }
};

var variants = {
  hidden: variants_hidden,
  visible: variants_visible
};

function Reviews(Props) {
  var match = ReactIntersectionObserver.useInView();
  var isHighlightsView = match[1];
  var match$1 = ReactIntersectionObserver.useInView();
  var isStudentsView = match$1[1];
  var controls = FramerMotion.useAnimation();
  var studentsControls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (isHighlightsView) {
            controls.start("visible");
          }
          
        }), [isHighlightsView]);
  React.useEffect((function () {
          if (isStudentsView) {
            studentsControls.start("visible");
          }
          
        }), [isStudentsView]);
  return React.createElement("div", {
              className: Review_Styles.wrapper,
              id: "reviews"
            }, React.createElement(Title.make, {
                  children: "Quem acredita no curso",
                  innerRef: match[0],
                  animate: {
                    NAME: "controlled",
                    VAL: controls
                  },
                  initial: "hidden",
                  variants: variants
                }), React.createElement("div", {
                  className: Review_Styles.reviews(false)
                }, Render.map(Reviews_Content.highlights, (function (review, id) {
                        var tmp = {
                          controls: controls,
                          id: id,
                          photo: review.photo,
                          name: review.name,
                          role: review.role,
                          description: review.description,
                          key: Render.toString(id)
                        };
                        if (review.translatedDescription !== undefined) {
                          tmp.translatedDescription = Caml_option.valFromOption(review.translatedDescription);
                        }
                        return React.createElement(ReviewItem.make, tmp);
                      }))), React.createElement("h2", {
                  ref: match$1[0],
                  className: Review_Styles.subtitle
                }, Render.str("Alunos do curso")), React.createElement("div", {
                  className: Review_Styles.reviews(true)
                }, Render.map(Reviews_Content.studentReviews, (function (review, id) {
                        return React.createElement(ReviewItem.make, {
                                    controls: studentsControls,
                                    id: id,
                                    photo: review.photo,
                                    name: review.name,
                                    role: review.role,
                                    description: review.description,
                                    isStudentReview: true,
                                    key: Render.toString(id)
                                  });
                      }))));
}

var make = Reviews;

exports.variants = variants;
exports.make = make;
/* Title Not a pure module */
