// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Review_Styles = require("./Review_Styles.bs.js");

function ReviewCard(Props) {
  var maybePhoto = Props.photo;
  var name = Props.name;
  var role = Props.role;
  var description = Props.description;
  return React.createElement("div", {
              className: Review_Styles.card
            }, React.createElement("div", {
                  className: Review_Styles.cardHeader
                }, maybePhoto !== undefined ? React.createElement("img", {
                        className: Review_Styles._photo,
                        src: maybePhoto
                      }) : null, React.createElement("div", undefined, React.createElement("h3", {
                          className: Review_Styles._name
                        }, name), React.createElement("p", {
                          className: Review_Styles._role
                        }, role))), React.createElement($$Text.P.make, {
                  children: description,
                  className: Review_Styles._description
                }));
}

var make = ReviewCard;

exports.make = make;
/* Text Not a pure module */
