// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var Review_Styles = require("./Review_Styles.bs.js");

function variants(delay) {
  return {
          hidden: {
            opacity: 0.0,
            y: 20
          },
          visible: {
            opacity: 1.0,
            y: 0,
            transition: {
              duration: 0.6,
              delay: delay
            }
          }
        };
}

function ReviewItem(Props) {
  var controls = Props.controls;
  var id = Props.id;
  var photo = Props.photo;
  var name = Props.name;
  var role = Props.role;
  var description = Props.description;
  var isStudentReviewOpt = Props.isStudentReview;
  var isStudentReview = isStudentReviewOpt !== undefined ? isStudentReviewOpt : false;
  var index = id;
  return React.createElement(Motion.Div.make, {
              className: Review_Styles.review(isStudentReview),
              initial: "hidden",
              variants: variants(index * 0.6),
              animate: {
                NAME: "controlled",
                VAL: controls
              },
              children: null
            }, React.createElement("div", {
                  className: Review_Styles.header
                }, React.createElement(Motion.Img.make, {
                      className: Review_Styles._photo(isStudentReview),
                      initial: "hidden",
                      variants: variants(index * 0.4),
                      animate: {
                        NAME: "controlled",
                        VAL: controls
                      },
                      src: photo
                    }), React.createElement("div", undefined, React.createElement(Motion.H2.make, {
                          className: Review_Styles._name,
                          initial: "hidden",
                          variants: variants(index * 0.5),
                          animate: {
                            NAME: "controlled",
                            VAL: controls
                          },
                          children: name
                        }), React.createElement(Motion.P.make, {
                          className: Review_Styles._role,
                          initial: "hidden",
                          variants: variants(index * 0.6),
                          animate: {
                            NAME: "controlled",
                            VAL: controls
                          },
                          children: role
                        }))), React.createElement($$Text.P.make, {
                  children: description,
                  className: Review_Styles._description(isStudentReview),
                  animate: {
                    NAME: "controlled",
                    VAL: controls
                  },
                  initial: "hidden",
                  variants: variants(index * 0.7)
                }));
}

var make = ReviewItem;

exports.variants = variants;
exports.make = make;
/* Text Not a pure module */
