// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var AnimatedJs = require("./Animated.js");

var make = AnimatedJs.FadeIn;

var FadeIn = {
  make: make
};

exports.FadeIn = FadeIn;
/* make Not a pure module */
