// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");
var React = require("react");

var title = CssJs.style([
      CssJs.color(CssJs.white),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontSize(CssJs.rem(3.2)),
      CssJs.position(CssJs.relative),
      CssJs.paddingLeft(CssJs.rem(4.8)),
      CssJs.marginBottom(CssJs.rem(3.2)),
      CssJs.after([
            CssJs.contentRule({
                  NAME: "url",
                  VAL: "assets/triangle-icon.svg"
                }),
            CssJs.width(CssJs.rem(3.2)),
            CssJs.height(CssJs.rem(3.2)),
            CssJs.position(CssJs.absolute),
            CssJs.left(CssJs.zero)
          ])
    ]);

function Title(Props) {
  var children = Props.children;
  return React.createElement("h1", {
              className: title
            }, children);
}

var make = Title;

exports.title = title;
exports.make = make;
/* title Not a pure module */
