// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Media = require("../../lib/Media.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      Media.xs([
            CssJs.padding2(CssJs.zero, CssJs.rem(3.2)),
            CssJs.margin4(CssJs.rem(17.2), CssJs.auto, CssJs.zero, CssJs.auto)
          ]),
      Media.sm([
            CssJs.maxWidth(Theme.Constants.maxWidth),
            CssJs.margin4(CssJs.rem(22.4), CssJs.auto, CssJs.zero, CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(4.6)),
            CssJs.flexDirection("columnReverse")
          ]),
      Media.md([
            CssJs.margin4(CssJs.rem(27.2), CssJs.auto, CssJs.rem(0.0), CssJs.auto),
            CssJs.padding2(CssJs.zero, CssJs.rem(4.6))
          ]),
      Media.xl([
            CssJs.flexDirection("row"),
            CssJs.margin4(CssJs.rem(32.4), CssJs.auto, CssJs.zero, CssJs.auto),
            CssJs.maxWidth(Theme.Constants.maxWidth),
            CssJs.padding2(CssJs.zero, CssJs.rem(5.6))
          ]),
      Media.xxl([CssJs.padding2(CssJs.zero, CssJs.zero)])
    ]);

var snippetWrapper = CssJs.style([
      CssJs.position(CssJs.relative),
      Media.xs([CssJs.display("none")]),
      Media.sm([
            CssJs.display("block"),
            CssJs.marginTop(CssJs.rem(4.2)),
            CssJs.minWidth(CssJs.pct(100.0))
          ]),
      Media.xl([
            CssJs.minWidth(CssJs.rem(62.0)),
            CssJs.left(CssJs.rem(-5.6))
          ]),
      CssJs.selector("pre", [
            Media.xl([CssJs.minWidth(CssJs.rem(62.0))]),
            CssJs.important(CssJs.margin(CssJs.zero)),
            CssJs.background(Theme.Colors.darkGradient),
            CssJs.borderRadius(Theme.Radius.xs),
            CssJs.fontSize(CssJs.rem(1.8)),
            CssJs.important(CssJs.padding4(CssJs.rem(1.8), CssJs.rem(3.2), CssJs.zero, CssJs.rem(3.2))),
            CssJs.height(CssJs.rem(42.0))
          ]),
      CssJs.selector(".Cursor", [CssJs.display(CssJs.none)])
    ]);

var content = CssJs.style([
      CssJs.display("flex"),
      CssJs.flexDirection(CssJs.column)
    ]);

var button = CssJs.style([
      CssJs.borderStyle(CssJs.none),
      CssJs.boxShadow(CssJs.none),
      CssJs.background(CssJs.none),
      CssJs.position(CssJs.relative),
      CssJs.padding4(CssJs.rem(1.2), CssJs.rem(5.6), CssJs.rem(1.2), CssJs.rem(2.0)),
      CssJs.cursor(CssJs.pointer),
      CssJs.alignSelf(CssJs.flexEnd),
      CssJs.selector("> span", [
            CssJs.color(Theme.Colors.purple),
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: Theme.fontFamily
                }),
            CssJs.fontSize(CssJs.rem(1.8)),
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 500
                }),
            CssJs.position(CssJs.relative),
            CssJs.zIndex(5),
            CssJs.transition(300, undefined, undefined, "color")
          ]),
      CssJs.after([
            CssJs.contentRule({
                  NAME: "url",
                  VAL: "assets/button-purple-arrow.svg"
                }),
            CssJs.width(CssJs.rem(2.4)),
            CssJs.height(CssJs.rem(1.6)),
            CssJs.position(CssJs.absolute),
            CssJs.right(CssJs.rem(2.0)),
            CssJs.top(CssJs.pct(50.0)),
            CssJs.marginTop(CssJs.rem(-0.8))
          ]),
      CssJs.before([
            CssJs.width(CssJs.zero),
            CssJs.contentRule({
                  NAME: "text",
                  VAL: " "
                }),
            CssJs.height(CssJs.pct(100.0)),
            CssJs.position(CssJs.absolute),
            CssJs.left(CssJs.zero),
            CssJs.top(CssJs.zero),
            CssJs.backgroundColor(Theme.Colors.purple),
            CssJs.borderRadius(CssJs.px(2)),
            CssJs.transition(200, undefined, undefined, "width")
          ]),
      CssJs.hover([
            CssJs.before([
                  CssJs.width(CssJs.pct(100.0)),
                  CssJs.transition(200, undefined, undefined, "width")
                ]),
            CssJs.selector("> span", [
                  CssJs.color(CssJs.white),
                  CssJs.transition(300, undefined, undefined, "color")
                ]),
            CssJs.after([
                  CssJs.contentRule({
                        NAME: "url",
                        VAL: "assets/button-white-arrow.svg"
                      }),
                  CssJs.transition(200, undefined, undefined, "content")
                ])
          ])
    ]);

var playgroundLink = CssJs.style([
      CssJs.position(CssJs.absolute),
      CssJs.right(CssJs.rem(3.2)),
      CssJs.bottom(CssJs.rem(2.8)),
      CssJs.color(Theme.Colors.pink),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontSize(CssJs.rem(1.4)),
      CssJs.fontWeight("bold"),
      CssJs.paddingRight(CssJs.rem(2.8)),
      CssJs.cursor(CssJs.pointer),
      CssJs.opacity(0.7),
      CssJs.transition(300, undefined, undefined, "opacity"),
      CssJs.textDecoration(CssJs.none),
      CssJs.hover([
            CssJs.opacity(1.0),
            CssJs.transition(300, undefined, undefined, "opacity"),
            CssJs.after([
                  CssJs.right(CssJs.px(-4)),
                  CssJs.transition(300, undefined, undefined, "right")
                ])
          ]),
      CssJs.after([
            CssJs.transition(300, undefined, undefined, "right"),
            CssJs.contentRule({
                  NAME: "url",
                  VAL: "assets/button-pink-arrow.svg"
                }),
            CssJs.position(CssJs.absolute),
            CssJs.right(CssJs.zero),
            CssJs.top(CssJs.pct(50.0)),
            CssJs.marginTop(CssJs.rem(-0.9)),
            CssJs.width(CssJs.rem(1.6)),
            CssJs.height(CssJs.rem(1.6))
          ])
    ]);

exports.wrapper = wrapper;
exports.snippetWrapper = snippetWrapper;
exports.content = content;
exports.button = button;
exports.playgroundLink = playgroundLink;
/* wrapper Not a pure module */
