// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var Title = require("../Title/Title.bs.js");
var React = require("react");
var FramerMotion = require("framer-motion");
var ReactIntersectionObserver = require("react-intersection-observer");

function variants(delay) {
  return {
          hidden: {
            opacity: 0.0,
            y: 20
          },
          visible: {
            opacity: 1.0,
            y: 0,
            transition: {
              duration: 0.6,
              delay: delay * 0.1
            }
          }
        };
}

function AboutRescript_Texts(Props) {
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  var controls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
          }
          
        }), [inView]);
  var animate = {
    NAME: "controlled",
    VAL: controls
  };
  return React.createElement("div", undefined, React.createElement(Title.make, {
                  children: "O que é ReScript?",
                  innerRef: match[0],
                  animate: animate,
                  initial: "hidden",
                  variants: variants(1.0)
                }), React.createElement($$Text.P.make, {
                  children: null,
                  animate: animate,
                  initial: "hidden",
                  variants: variants(3.0)
                }, React.createElement($$Text.make, {
                      children: "ReScript"
                    }), React.createElement($$Text.Span.make, {
                      children: " (anteriormente ReasonML) "
                    }), React.createElement($$Text.make, {
                      children: "é uma linguagem focada em React \n          e no ecossistema JavaScropt. Criada dentro do Facebook, a linguagem tem \n          como objetivo trazer uma síntaxe amigável aos desenvolvedores(as) JavaScript, \n          com um poderoso sistema de tipos e diversas features de programação funcional."
                    })), React.createElement($$Text.P.make, {
                  children: "Por compartilhar do mesmo criador do React, ReScript possui \n        diversas features pensadas do zero para integração com o mesmo, \n        contando inclusive com um ótimo suporte a JSX nativo no seu compilador.",
                  animate: animate,
                  initial: "hidden",
                  variants: variants(6.0)
                }), React.createElement($$Text.P.make, {
                  children: "\n        Além disso, a linguagem foi pensada desde o início em interoperar com \n        códigos e bibliotecas escritas em JavaScript. O que significa, que \n        qualquer biblioteca JavaScript, pode ser utilizada com ReScript. \n      ",
                  animate: animate,
                  initial: "hidden",
                  variants: variants(9.0)
                }));
}

var make = AboutRescript_Texts;

exports.variants = variants;
exports.make = make;
/* Text Not a pure module */
