// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var AboutRescript_Texts = require("./AboutRescript_Texts.bs.js");
var AboutReScript_Styles = require("./AboutReScript_Styles.bs.js");
var AboutRescript_Snippet = require("./AboutRescript_Snippet.bs.js");

var variants_hidden = {
  opacity: 0.0,
  y: 20
};

var variants_visible = {
  opacity: 1.0,
  y: 0,
  transition: {
    duration: 0.6,
    delay: 0.35
  }
};

var variants = {
  hidden: variants_hidden,
  visible: variants_visible
};

function AboutReScript(Props) {
  return React.createElement("section", {
              className: AboutReScript_Styles.wrapper,
              id: "o-que-e-rescript"
            }, React.createElement(AboutRescript_Snippet.make, {}), React.createElement("div", {
                  className: AboutReScript_Styles.content
                }, React.createElement(AboutRescript_Texts.make, {})));
}

var SnippetExample;

var Texts;

var make = AboutReScript;

exports.SnippetExample = SnippetExample;
exports.Texts = Texts;
exports.variants = variants;
exports.make = make;
/* react Not a pure module */
