// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var SnippetJs = require("./Snippet.js");
var AboutReScript_Styles = require("./AboutReScript_Styles.bs.js");

var make = SnippetJs.Snippet;

var Snippet = {
  make: make
};

var link = "https://rescript-lang.org/try?code=AIJwpghgxgLgdFA9gWwA6IHZgzAUAGzBgAJkIBrMYgXmIAoBKGgPmIG9djjCS6BnABaIA7gBpifIgGUhwprQBKkWHACukqTAgwwdAPotiAMwj5JDTsQA8AEwCWAN2aWAkNdTO3XdoJHEA-MRK0PB8MCB2GADmdABEABJg+PiIAISxTABcQcrwGKrJAL6WXFYA9B64XtYARqowMJjEmADC+HZQ5NRsBtSskjAyIvqGqb5yhZ7e7MEqYRHRcW0d5MQCYOAZxdXldQ2YzqVl9k64hUA";

function AboutRescript_Snippet(Props) {
  var showSnippets = Props.showSnippets;
  return React.createElement("div", {
              className: AboutReScript_Styles.snippetWrapper
            }, React.createElement(make, {
                  showSnippets: showSnippets
                }), React.createElement("a", {
                  className: AboutReScript_Styles.playgroundLink,
                  href: link,
                  target: "_blank"
                }, "Abrir no playground"));
}

var make$1 = AboutRescript_Snippet;

exports.Snippet = Snippet;
exports.link = link;
exports.make = make$1;
/* make Not a pure module */
