// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var SnippetJs = require("./Snippet.js");
var FramerMotion = require("framer-motion");
var AboutReScript_Styles = require("./AboutReScript_Styles.bs.js");
var ReactIntersectionObserver = require("react-intersection-observer");

var make = SnippetJs.Snippet;

var Snippet = {
  make: make
};

var link = "https://rescript-lang.org/try?code=AIJwpghgxgLgdFA9gWwA6IHZgzAUAGzBgAJkIBrMYgXmIAoBKGgPmIG9djjCS6BnABaIA7gBpifIgGUhwprQBKkWHACukqTAgwwdAPotiAMwj5JDTsQA8AEwCWAN2aWAkNdTO3XdoJHEA-MRK0PB8MCB2GADmdABEABJg+PiIAISxTABcQcrwGKrJAL6WXFYA9B64XtYARqowMJjEmADC+HZQ5NRsBtSskjAyIvqGqb5yhZ7e7MEqYRHRcW0d5MQCYOAZxdXldQ2YzqVl9k64hUA";

var variants_hidden = {
  opacity: 0.0,
  y: 20
};

var variants_visible = {
  opacity: 1.0,
  y: 0,
  transition: {
    duration: 0.6,
    delay: 0.35
  }
};

var variants = {
  hidden: variants_hidden,
  visible: variants_visible
};

function AboutRescript_Snippet(Props) {
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setShowSnippets = match$1[1];
  var controls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
            Curry._1(setShowSnippets, (function (param) {
                    return true;
                  }));
          }
          
        }), [inView]);
  return React.createElement(Motion.Div.make, {
              className: AboutReScript_Styles.snippetWrapper,
              initial: "hidden",
              variants: variants,
              animate: {
                NAME: "controlled",
                VAL: controls
              },
              innerRef: match[0],
              children: null
            }, React.createElement(make, {
                  showSnippets: match$1[0]
                }), React.createElement("a", {
                  className: AboutReScript_Styles.playgroundLink,
                  href: link,
                  rel: "noopener noreferrer",
                  target: "_blank"
                }, "Abrir no playground"));
}

var make$1 = AboutRescript_Snippet;

exports.Snippet = Snippet;
exports.link = link;
exports.variants = variants;
exports.make = make$1;
/* make Not a pure module */
