// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var React = require("react");

var logo = CssJs.style([CssJs.width(CssJs.rem(30.0))]);

var S = {
  logo: logo
};

function Logo(Props) {
  return React.createElement("img", {
              className: logo,
              alt: "EcmaScript2077 | Incoming from the future",
              src: "assets/white-logo.svg"
            });
}

var make = Logo;

exports.S = S;
exports.make = make;
/* logo Not a pure module */
