// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Media = require("../../lib/Media.bs.js");
var React = require("react");

var logo = CssJs.style([
      Media.md([CssJs.width(CssJs.rem(28.0))]),
      Media.sm([CssJs.width(CssJs.rem(26.0))]),
      Media.xs([CssJs.display("none")])
    ]);

var logoMinimal = CssJs.style([
      CssJs.width(CssJs.rem(16.2)),
      CssJs.display(CssJs.none),
      Media.xs([CssJs.display("block")])
    ]);

function Logo(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("img", {
                  className: logo,
                  alt: "EcmaScript2077 | Incoming from the future",
                  src: "assets/white-logo.svg"
                }), React.createElement("img", {
                  className: logoMinimal,
                  alt: "EcmaScript2077 | Incoming from the future",
                  src: "assets/logo-minimal.svg"
                }));
}

var make = Logo;

exports.logo = logo;
exports.logoMinimal = logoMinimal;
exports.make = make;
/* logo Not a pure module */
