// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var React = require("react");

var wrapper = CssJs.style([CssJs.padding2(CssJs.rem(5.6), CssJs.rem(15.0))]);

var S = {
  wrapper: wrapper
};

function Layout(Props) {
  var children = Props.children;
  return React.createElement("div", {
              className: wrapper
            }, children);
}

var make = Layout;

exports.S = S;
exports.make = make;
/* wrapper Not a pure module */
