// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var About_Styles = require("./About_Styles.bs.js");
var About_Concepts = require("./About_Concepts.bs.js");

function About(Props) {
  return React.createElement("section", {
              className: About_Styles.wrapper
            }, React.createElement(Title.make, {
                  children: "Sobre o curso"
                }), React.createElement("p", {
                  className: About_Styles.text
                }, "\n        O objetivo do curso é te ensinar do zero, como desenvolver aplicações com ReScript, \n        utilizando React e outras bibliotecas existentes, além das próprias ferramentas do \n        ecossistema ReScript. Além disso, você irá aprender de forma prática e descomplicada, \n        vários conceitos de programação funcional e como aplicar esses conceitos no desenvolvimento de aplicações reais. \n        Além dos módulos e conteúdo do curso, você terá acesso total ao suporte dos instrutores e acesso ao discord \n        oficial do curso, podendo entrar em contato para tirar dúvidas sempre que necessário.\n      "), React.createElement(About_Concepts.make, {}));
}

var Concepts;

var make = About;

exports.Concepts = Concepts;
exports.make = make;
/* Title Not a pure module */
