// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");

var descriptionText = React.createElement(React.Fragment, undefined, Render.str("Você irá aprender de forma "), React.createElement($$Text.Span.make, {
          children: "prática"
        }), Render.str(" e"), React.createElement($$Text.Span.make, {
          children: " descomplicada"
        }), Render.str(", diversos conceitos relacionados a programação funcional e como aplicá-los no seu dia a dia."));

exports.descriptionText = descriptionText;
/* descriptionText Not a pure module */
