// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var About_Styles = require("./About_Styles.bs.js");
var AnimatedJs = require("./Animated.js");
var FramerMotion = require("framer-motion");
var ReactIntersectionObserver = require("react-intersection-observer");

var make = AnimatedJs.Topic;

var Topic = {
  make: make
};

var concepts = [
  "Filosofia e conceitos da linguagem",
  "Setup e Tooling de projetos",
  "Type Driven Development",
  "Interoperabilidade com JavaScript",
  "Integrações REST e GraphQL",
  "CSS in ReScript",
  "Integração com React",
  "Programação Funcional"
];

function About_Concepts(Props) {
  var controls = FramerMotion.useAnimation();
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
          }
          
        }), [inView]);
  return React.createElement("div", {
              ref: match[0],
              className: About_Styles.conceptsWrapper
            }, React.createElement("p", {
                  className: About_Styles.conceptsText
                }, React.createElement($$Text.make, {
                      children: "Você irá aprender de forma "
                    }), React.createElement($$Text.Span.make, {
                      children: "prática"
                    }), React.createElement($$Text.make, {
                      children: " e"
                    }), React.createElement($$Text.Span.make, {
                      children: " descomplicada"
                    }), React.createElement($$Text.make, {
                      children: ", diversos conceitos relacionados a programação funcional e como aplicá-los no seu dia a dia."
                    })), React.createElement("ul", {
                  className: About_Styles.topicsList
                }, Render.map(concepts, (function (text, index) {
                        return React.createElement(make, {
                                    children: text,
                                    index: index,
                                    animate: controls,
                                    key: Render.toString(index)
                                  });
                      }))));
}

var make$1 = About_Concepts;

exports.Topic = Topic;
exports.concepts = concepts;
exports.make = make$1;
/* make Not a pure module */
