// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");
var Belt_Array = require("bs-platform/lib/js/belt_Array.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin4(CssJs.zero, CssJs.auto, CssJs.rem(0.0), CssJs.auto),
      CssJs.padding2(CssJs.rem(12.4), CssJs.zero)
    ]);

var conceptsWrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems(CssJs.center),
      CssJs.justifyContent(CssJs.spaceBetween),
      CssJs.marginTop(CssJs.rem(6.4))
    ]);

var conceptsText = CssJs.style([
      CssJs.color(Theme.Colors.white),
      CssJs.fontSize(CssJs.rem(3.2)),
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontWeight({
            NAME: "num",
            VAL: 800
          }),
      CssJs.marginRight(CssJs.rem(6.4)),
      CssJs.selector("> span", Belt_Array.concat([CssJs.background(Theme.Colors.gradient)], Theme.Constants.clipBackground))
    ]);

var topicsList = CssJs.style([
      CssJs.minWidth(CssJs.rem(42.0)),
      CssJs.listStyleType(CssJs.none),
      CssJs.padding(CssJs.zero),
      CssJs.margin(CssJs.zero),
      CssJs.selector("> li", [
            CssJs.paddingLeft(CssJs.rem(4.0)),
            CssJs.marginBottom(CssJs.rem(1.2)),
            CssJs.color(Theme.Colors.text),
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: Theme.fontFamily
                }),
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 600
                }),
            CssJs.fontSize(CssJs.rem(1.8)),
            CssJs.position(CssJs.relative),
            CssJs.after([
                  CssJs.contentRule({
                        NAME: "url",
                        VAL: "assets/check-icon.svg"
                      }),
                  CssJs.width(CssJs.rem(2.4)),
                  CssJs.height(CssJs.rem(2.4)),
                  CssJs.position(CssJs.absolute),
                  CssJs.left(CssJs.zero),
                  CssJs.top(CssJs.pct(50.0)),
                  CssJs.marginTop(CssJs.rem(-1.2))
                ])
          ])
    ]);

var $$Array;

exports.$$Array = $$Array;
exports.wrapper = wrapper;
exports.conceptsWrapper = conceptsWrapper;
exports.conceptsText = conceptsText;
exports.topicsList = topicsList;
/* wrapper Not a pure module */
