// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

function MakeElement(M) {
  var Motion_Components$MakeElement = function (Props) {
    var className = Props.className;
    var initial = Props.initial;
    var variants = Props.variants;
    var animate = Props.animate;
    var innerRef = Props.innerRef;
    var id = Props.id;
    var children = Props.children;
    var tmp = {};
    if (className !== undefined) {
      tmp.className = Caml_option.valFromOption(className);
    }
    if (innerRef !== undefined) {
      tmp.ref = Caml_option.valFromOption(innerRef);
    }
    if (id !== undefined) {
      tmp.id = Caml_option.valFromOption(id);
    }
    if (initial !== undefined) {
      tmp.initial = Caml_option.valFromOption(initial);
    }
    if (variants !== undefined) {
      tmp.variants = Caml_option.valFromOption(variants);
    }
    if (animate !== undefined) {
      tmp.animate = Caml_option.valFromOption(animate);
    }
    var props = tmp;
    return React.createElement(M.element, props, children);
  };
  return {
          make: Motion_Components$MakeElement
        };
}

exports.MakeElement = MakeElement;
/* react Not a pure module */
