// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Hero = require("../components/Hero/Hero.bs.js");
var About = require("../components/About/About.bs.js");
var React = require("react");
var Header = require("../components/Header/Header.bs.js");
var Layout = require("../components/Layout/Layout.bs.js");
var AboutUs = require("../components/AboutUs/AboutUs.bs.js");
var AboutReScript = require("../components/AboutReScript/AboutReScript.bs.js");

function $$default(param) {
  return React.createElement(Layout.make, {
              children: null
            }, React.createElement(Header.make, {}), React.createElement(Hero.make, {}), React.createElement(AboutReScript.make, {}), React.createElement(About.make, {}), React.createElement(AboutUs.make, {}), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined), React.createElement("br", undefined));
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Hero Not a pure module */
