// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Header = require("../components/Header/Header.bs.js");
var Layout = require("../components/Layout/Layout.bs.js");

function $$default(param) {
  return React.createElement(Layout.make, {
              children: React.createElement(Header.make, {})
            });
}

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
