// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Logo = require("../Logo/Logo.bs.js");
var Menu = require("../Menu/Menu.bs.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var Header_Styles = require("./Header_Styles.bs.js");

var variants_hidden = {
  opacity: 0.0,
  y: -20
};

var variants_visible = {
  opacity: 1.0,
  y: 0,
  transition: {
    duration: 0.6,
    delay: 0.35
  }
};

var variants = {
  hidden: variants_hidden,
  visible: variants_visible
};

function Header(Props) {
  return React.createElement(Motion.Header.make, {
              className: Header_Styles.wrapper,
              initial: "hidden",
              variants: variants,
              animate: "visible",
              children: null
            }, React.createElement(Logo.make, {}), React.createElement(Menu.make, {}));
}

var make = Header;

exports.variants = variants;
exports.make = make;
/* Logo Not a pure module */
