// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin2(CssJs.zero, "auto")
    ]);

exports.wrapper = wrapper;
/* wrapper Not a pure module */
