// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Logo = require("../Logo/Logo.bs.js");
var React = require("react");
var Header_Styles = require("./Header_Styles.bs.js");

function Header(Props) {
  return React.createElement("header", {
              className: Header_Styles.wrapper
            }, React.createElement(Logo.make, {}));
}

var make = Header;

exports.make = make;
/* Logo Not a pure module */
