// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin4(CssJs.zero, CssJs.auto, CssJs.rem(0.0), CssJs.auto),
      CssJs.padding2(CssJs.rem(12.4), CssJs.zero),
      CssJs.display("flex"),
      CssJs.justifyContent("center"),
      CssJs.alignItems("center"),
      CssJs.flexDirection(CssJs.column)
    ]);

var link = CssJs.style([
      CssJs.cursor(CssJs.pointer),
      CssJs.textDecoration(CssJs.none)
    ]);

var partner = CssJs.style([
      CssJs.padding(CssJs.rem(11.8)),
      CssJs.display("flex"),
      CssJs.justifyContent("center"),
      CssJs.alignItems("center"),
      CssJs.flexDirection(CssJs.column),
      CssJs.borderRadius(CssJs.px(6)),
      CssJs.transition(400, undefined, undefined, "background"),
      CssJs.position(CssJs.relative),
      CssJs.marginRight(CssJs.rem(3.2)),
      CssJs.hover([
            CssJs.background(CssJs.hex("0f0f0f")),
            CssJs.transition(400, undefined, undefined, "background"),
            CssJs.selector("path", [
                  CssJs.unsafe("fill", "#ffffff"),
                  CssJs.transition(400, undefined, undefined, "fill")
                ]),
            CssJs.selector("p", [
                  CssJs.transition(400, undefined, undefined, "color"),
                  CssJs.color(Theme.Colors.white)
                ]),
            CssJs.selector("img", [
                  CssJs.transitionDuration(400),
                  CssJs.unsafe("filter", "brightness(5.5)")
                ])
          ]),
      CssJs.selector("p", [
            CssJs.transition(400, undefined, undefined, "color"),
            CssJs.position(CssJs.absolute),
            CssJs.bottom(CssJs.rem(4.0)),
            CssJs.left(CssJs.pct(50.0)),
            CssJs.transform(CssJs.translateX(CssJs.pct(-50.0))),
            CssJs.marginTop(CssJs.rem(3.2)),
            CssJs.fontFamily({
                  NAME: "custom",
                  VAL: Theme.fontFamily
                }),
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 700
                }),
            CssJs.fontSize(CssJs.rem(2.4)),
            CssJs.color(CssJs.transparent)
          ]),
      CssJs.selector("svg, img", [CssJs.width(CssJs.rem(9.6))]),
      CssJs.selector("img", [
            CssJs.transitionDuration(400),
            CssJs.unsafe("filter", "contrast(0.5%)")
          ]),
      CssJs.selector("path", [CssJs.transition(400, undefined, undefined, "fill")])
    ]);

var partners = CssJs.style([
      CssJs.display("flex"),
      CssJs.marginTop(CssJs.rem(5.2))
    ]);

exports.wrapper = wrapper;
exports.link = link;
exports.partner = partner;
exports.partners = partners;
/* wrapper Not a pure module */
