// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Title = require("../Title/Title.bs.js");
var React = require("react");
var Partners_Logo = require("./Partners_Logo.bs.js");
var Partners_Styles = require("./Partners_Styles.bs.js");

function Partners(Props) {
  return React.createElement("div", {
              className: Partners_Styles.wrapper
            }, React.createElement(Title.make, {
                  children: "Nossos parceiros"
                }), React.createElement("div", {
                  className: Partners_Styles.partners
                }, React.createElement("div", {
                      className: Partners_Styles.partner
                    }, React.createElement(Partners_Logo.Brainn.make, {}), React.createElement("p", undefined, "Brainn Co.")), React.createElement("div", {
                      className: Partners_Styles.partner
                    }, React.createElement(Partners_Logo.ReasonBR.make, {}), React.createElement("p", undefined, "ReasonBR")), React.createElement("div", {
                      className: Partners_Styles.partner
                    }, React.createElement(Partners_Logo.Brainn.make, {}), React.createElement("p", undefined, "Astrocoders"))));
}

var Logos;

var make = Partners;

exports.Logos = Logos;
exports.make = make;
/* Title Not a pure module */
