// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");

var releasingText = React.createElement(React.Fragment, undefined, Render.str("Este será um curso vivo, onde os módulos serão lançados conforme o desenvolvimento. \n      No momento, estamos desenvolvendo os 2 primeiros módulos e o lançamento oficial deverá ocorrer no dia "), React.createElement($$Text.Span.make, {
          children: "30/04/2020"
        }), Render.str(". Caso você não queira perder o lançamento, nós podemos lhe comunicar via e-mail com antecedência."));

exports.releasingText = releasingText;
/* releasingText Not a pure module */
