// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Releasing(Props) {
  return React.createElement("div", undefined);
}

var make = Releasing;

exports.make = make;
/* react Not a pure module */
