// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var $$Text = require("../Text/Text.bs.js");
var Title = require("../Title/Title.bs.js");
var React = require("react");
var Motion = require("../../bindings/FramerMotion/Motion.bs.js");
var Render = require("../../lib/Render.bs.js");
var FramerMotion = require("framer-motion");
var Releasing_Styles = require("./Releasing_Styles.bs.js");
var Releasing_Content = require("./Releasing_Content.bs.js");
var ReactIntersectionObserver = require("react-intersection-observer");

function variants(delay) {
  return {
          hidden: {
            opacity: 0.0,
            y: 20
          },
          visible: {
            opacity: 1.0,
            y: 0,
            transition: {
              duration: 0.6,
              delay: delay
            }
          }
        };
}

function Releasing(Props) {
  var match = ReactIntersectionObserver.useInView();
  var inView = match[1];
  var controls = FramerMotion.useAnimation();
  React.useEffect((function () {
          if (inView) {
            controls.start("visible");
          }
          
        }), [inView]);
  return React.createElement(Motion.Div.make, {
              className: Releasing_Styles.wrapper,
              initial: "hidden",
              variants: variants(0.2),
              animate: {
                NAME: "controlled",
                VAL: controls
              },
              children: React.createElement("div", {
                    className: Releasing_Styles.content
                  }, React.createElement(Title.make, {
                        children: "Pré-Lançamento",
                        innerRef: match[0],
                        animate: {
                          NAME: "controlled",
                          VAL: controls
                        },
                        initial: "hidden",
                        variants: variants(0.4),
                        icon: "lighting"
                      }), React.createElement($$Text.P.make, {
                        children: Releasing_Content.releasingText,
                        className: Releasing_Styles.text,
                        animate: {
                          NAME: "controlled",
                          VAL: controls
                        },
                        initial: "hidden",
                        variants: variants(0.2)
                      }), React.createElement($$Text.P.make, {
                        children: null,
                        className: Releasing_Styles.text,
                        animate: {
                          NAME: "controlled",
                          VAL: controls
                        },
                        initial: "hidden",
                        variants: variants(0.2)
                      }, React.createElement("i", undefined, Render.str("Fique tranquilo, nós não enviamos spam!")), Render.str(" 😉")), React.createElement(Motion.Div.make, {
                        className: Releasing_Styles.form,
                        initial: "hidden",
                        variants: variants(0.2),
                        animate: {
                          NAME: "controlled",
                          VAL: controls
                        },
                        children: null
                      }, React.createElement("input", {
                            placeholder: "Digite aqui o seu melhor e-mail"
                          }), React.createElement("button", undefined, "Enviar")))
            });
}

var Content;

var make = Releasing;

exports.Content = Content;
exports.variants = variants;
exports.make = make;
/* Text Not a pure module */
