// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Logo = require("../Logo/Logo.bs.js");
var React = require("react");
var Render = require("../../lib/Render.bs.js");
var Footer_Styles = require("./Footer_Styles.bs.js");

function Footer(Props) {
  return React.createElement("footer", {
              className: Footer_Styles.wrapper
            }, React.createElement("div", {
                  className: Footer_Styles.content
                }, React.createElement(Logo.make, {}), React.createElement("p", {
                      className: Footer_Styles.madeBy
                    }, Render.str("Design por"), React.createElement("a", {
                          href: "https://dribbble.com/rebgonzalez",
                          rel: "noopener noreferrer"
                        }, Render.str(" Rebecca Gonzalez")))));
}

var make = Footer;

exports.make = make;
/* Logo Not a pure module */
