// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var CssJs = require("bs-css-emotion/src/CssJs.bs.js");
var Theme = require("../../lib/Theme.bs.js");

var wrapper = CssJs.style([CssJs.background(Theme.Colors.darkGradient)]);

var content = CssJs.style([
      CssJs.maxWidth(Theme.Constants.maxWidth),
      CssJs.margin4(CssJs.zero, CssJs.auto, CssJs.zero, CssJs.auto),
      CssJs.padding2(CssJs.rem(6.4), CssJs.zero),
      CssJs.display("flex"),
      CssJs.alignItems("center"),
      CssJs.justifyContent("spaceBetween")
    ]);

var madeBy = CssJs.style([
      CssJs.fontFamily({
            NAME: "custom",
            VAL: Theme.fontFamily
          }),
      CssJs.fontSize(CssJs.rem(1.6)),
      CssJs.color(CssJs.hex("AD9FC6")),
      CssJs.selector("> a", [
            CssJs.fontWeight({
                  NAME: "num",
                  VAL: 600
                }),
            CssJs.color(Theme.Colors.pink),
            CssJs.textDecoration(CssJs.none),
            CssJs.position(CssJs.relative),
            CssJs.hover([CssJs.after([
                        CssJs.transition(300, undefined, undefined, "transform"),
                        CssJs.transform(CssJs.scale(1.0, 1.0))
                      ])]),
            CssJs.after([
                  CssJs.transition(300, undefined, undefined, "transform"),
                  CssJs.contentRule({
                        NAME: "text",
                        VAL: " "
                      }),
                  CssJs.position(CssJs.absolute),
                  CssJs.bottom(CssJs.px(-4)),
                  CssJs.left(CssJs.zero),
                  CssJs.width(CssJs.pct(100.0)),
                  CssJs.height(CssJs.px(2)),
                  CssJs.background(Theme.Colors.pink),
                  CssJs.transform(CssJs.scale(0.0, 0.0))
                ])
          ])
    ]);

exports.wrapper = wrapper;
exports.content = content;
exports.madeBy = madeBy;
/* wrapper Not a pure module */
