// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var GlobalStyles = require("./lib/GlobalStyles.bs.js");

GlobalStyles.addStyles(undefined);

var PageComponent = {};

function $$default(props) {
  return React.createElement(props.Component, props.pageProps);
}

exports.PageComponent = PageComponent;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/*  Not a pure module */
